name: Docker build and push 

on:
  workflow_dispatch:
  push:
    paths:
      - "Dockerfile"
      - "requirements.txt"
      - "**/*.py"
    branches:
      - main 

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/aks_demo:latest
            ${{ secrets.DOCKER_USERNAME }}/aks_demo:${{ github.run_number }}
